linuxmint/webapp-manager

usr/share/webapp-manager/webapp-manager.ui
use document-edit-symbolic instead of list-edit-symbolic as it does not exist on at least on Ubuntu 20.04.1
=> use document-edit-symbolic

usr/share/webapp-manager/webapp-manager.ui
Simple fix. Just center the switches instead of having them fill the entire
horizontal space.
Fixes: https://github.com/linuxmint/webapp-manager/issues/27
=> ui: Fix stretched switches

usr/lib/webapp-manager/common.py
ref: https://github.com/linuxmint/xapp/pull/127
=> Override the icon for firefox webapps (otherwise it gets them wrong in mate and xfce)

usr/lib/webapp-manager/common.py
Add possibility to use Vivaldi Snapshot if it's installed (issue #56)
=> Allow using Vivaldi Snapshot as app's browser

README.md
Points out you can still copy and paste links from the webapp to your main browser.
=> 'copy link location' to open links in main browser

usr/lib/webapp-manager/webapp-manager.py
This PR fixes and closes the following issues:
1. Feature Request: Confirm on Delete #66
2. Add a Confirm dialogue before app removal #75
Tested on:
1. Ubuntu Mate 20.04.2
2. Ubuntu 20.10
3. Ubuntu 21.04
closes #66, closes #75
=> [Feature] Confirmation dialog before deletion

usr/lib/webapp-manager/common.py
This fix contains the errors related to launching in
Epiphany aka GNOME Web.
Epiphany follows very strict method implementing app-mode.
The profile directory should be in `~/.local/share`,
profile name should start with `org.gnome.Epiphany.WebApp-` and
the icon should be located in the profile directory with name `app-icon.png`
Known issues/bugs:
1. when a web-app is created with icons from system theme, the web-app will fail to launch because the icon is not copied to profile directory.
EDIT:
This PR is probably irrelevant because Epiphany from apt repo in Ubuntu 20.04 uses prefix `epiphany-` while Epiphany in Ubuntu 21.04 uses `org.gnome.Epiphany.WebApp-`. So I shall leave the decision to LM maintainers whether to keep this PR or not.
=> Fix for epiphany; fixes #104

usr/share/webapp-manager/firefox/profile/user.js
Enable cookie isolation for enhanced privacy. Facilitate #149 by enabling cookies in Librewolf (and any other browsers that clears cookies by default).
=> Improve cookie management in Firefox & Librewolf

usr/lib/webapp-manager/common.py
Only return the results from Favicon Grabber if they are not empty and
the request succeeded.
Scan for all icons with a given format, as they can come in different
sizes, particularly those defined as apple-touch-icon.
Fix msapplication-TileImage finding, which is encoded in a meta tag
rather tan a rel one. See:
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024(v=vs.85)
Add a few other Microsoft formats, as per the same page.
Redactor and simplify handling slightly by defining parsers for each
type of URL.
=> Improve icon detection

usr/lib/webapp-manager/common.py, usr/lib/webapp-manager/webapp-manager.py, usr/share/webapp-manager/webapp-manager.ui
This PR adds support for custom parameters. This allows parameters to be added to the browser executable without editing the .desktop file, which will still be overwritten when editing an entry in the web application manager.
=> Implemented custom browser parameters

usr/lib/webapp-manager/common.py
Properly quotes the XAPP_FORCE_GTK_WINDOW_ICON env so spaces in icon path no longer prevents it from launching.
Resolves #150
=> Fix spaces in icon path from breaking webapps

usr/lib/webapp-manager/common.py
Add the ability to use flatpak-ed variant of Brave as a target browser for Webapps.
Relates to https://www.reddit.com/r/linuxmint/comments/xgb4t4/webapp_manager_grayed_out_options/
May also relate to #192
=> Add Brave (flatpak) as target browser

usr/lib/webapp-manager/common.py
This resolves an issue where certain characters (for example &) were being interpreted by `sh` in the EXEC portion of the desktop entry. This may result in only a portion of the URL being forwarded to the target browser to display.
See: issue #180
=> Add quotes around url in EXEC

debian/changelog, usr/lib/webapp-manager/common.py, usr/lib/webapp-manager/webapp-manager.py
* navbar switch
* isolate profile switch
* private window switch
> didn't test yet, will undraft when i have time to test and assert it works.
=> Edit webapp browser settings

usr/lib/webapp-manager/common.py
Or else I get this error:
```
Traceback (most recent call last):                                                                                                                    
File "/usr/lib/webapp-manager/webapp-manager.py", line 25, in <module>
from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
File "/usr/lib/webapp-manager/common.py", line 213
Browser(BROWSER_TYPE_CHROMIUM, "Brave (Flatpak)", ".local/share/flatpak/exports/bin/com.brave.Browser", ".local/share/flatpak/exports/bin/com.brave.Browser")
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```
=> Add missing comma in common.py

usr/lib/webapp-manager/common.py
Adds Naver Whale [browser used in HarmoniKR OS] and Falkon as a Flatpak.
=> Add Falkon (Flatpak) and Naver Whale browser

usr/share/webapp-manager/firefox/profile/chrome/userChrome.css
I found that removing "!important" from the rule in userChrome.css did not cause the navbar to be displayed, so I modified the file a bit to display the navbar's children (and their children, recursively - otherwise it doesn't work). The result is that you can now install extensions without temporarily altering the userChrome.css file, and also permission pop-ups work instead of flickering endlessly.
closes #235 , closes #211 , closes #168 , closes #145
=> Display navbar children to fix pop-ups on firefox

usr/lib/webapp-manager/common.py
Fixes a problem in Gnome wayland with handling the window names.
Closes https://github.com/linuxmint/webapp-manager/issues/103
=> Fix Gnome wayland handling window names

usr/share/webapp-manager/firefox/profile/chrome/userChrome.css
Hiding navigation toolbars is nice most of the time, however sometimes you have several tabs open either on purpose or by accident, and want to close some of them. (e.g. #101, #105, #266)
But going back into the webapp-manager to edit the "hide navigation bar" option is inconvenient especially when you must do this every single time there are extraneous tabs.
In fact Firefox already has a nice feature that hides the menubar when it's not needed, and shows it only when it's needed - the Alt button.
This PR hooks the rest of the navigation bar onto this mechanism, so pressing Alt will now toggle the menubar+navbars together.
On my version of Firefox (latest) it's not necessary to explicitly style `#identity-box, #tabbrowser-tabs` since they are inside the other elements, I'm not sure of the …
=> Firefox: hide navigation toolbars only when top menu is inactive

usr/lib/webapp-manager/common.py
Uses "WebApp-" as the prefix for all new shortcuts while retaining support for existing "webapp-" shortcuts.
Fixes #82
=> Fix capitalization of WebApp

usr/share/webapp-manager/firefox/profile/chrome/userChrome.css
Ref #320
This change updates the `userChrome.css` file in your webapp's profile.
To try it, you can:
- Back up the current package's file:
```
$ cd /usr/share/webapp-manager/firefox/profile/chrome
$ sudo mv userChrome.css userChrome.css.bak
```
- Create the file with [new contents](https://github.com/linuxmint/webapp-manager/blob/ef8855f711bd4db7c74cb1e3d195cadda98b4e6f/usr/share/webapp-manager/firefox/profile/chrome/userChrome.css):
```
> curl https://raw.githubusercontent.com/linuxmint/webapp-manager/ef8855f711bd4db7c74cb1e3d195cadda98b4e6f/usr/share/webapp-manager/firefox/profile/chrome/userChrome.css | sudo tee ./userChrome.css
```
- Then, start webapp-manager and Edit the webapp. Click Ok without any changes - this should update your webapp with the new userChrome.css file. Next time …
=> userChrome.css: Adapt to firefox 133 layout changes.

usr/lib/webapp-manager/common.py
As mentioned in #312 the certificate of  [https://favicongrabber.com/](https://favicongrabber.com/) has expired. Additionally, the site has not been functioning properly since 2021 and is running outdated, vulnerable software. Since we have no control over this site, I removed the call to its API.
This change might be worth backporting to all currently supported versions of Linux Mint.
=> Remove call to favicongrabber.com

usr/lib/webapp-manager/common.py
Currently, the downloaded images are added to the result list regardless of whether the save operation was successful. If the save failed, `webapp-manager` still attempts to display the preview, which results in a blank image, as shown below:
I modified the behavior to ensure that only successfully saved images are added to the result list. This will prevent the display of blank previews for failed saves.
=> Prevent preview of unsaved images

usr/lib/webapp-manager/webapp-manager.py
Replaced manual resource management for the license file with the `with` statement to ensure it always gets closed. Additionally, since concatenating the results of `readlines()` reconstructs the original file content, `read() `is used directly instead for simplicity and efficiency.
=> Use auto resource management for license file
