usr/lib/webapp-manager/webapp-manager.py

Add Education category

---

usr/lib/webapp-manager/common.py

XDG_DATA_HOME has been chosen as a directory to store profiles based on
https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories

Support for Firefox Flatpak profiles

---

usr/lib/webapp-manager/common.py

Add Microsoft Edge browser support

Add support for Microsoft Edge

---

usr/lib/webapp-manager/common.py

and add a custom path for another browser

add support for Chromium installed as Flatpak package

---

usr/lib/webapp-manager/common.py

fixes: https://github.com/linuxmint/webapp-manager/issues/71

add support for Chromium installed as Snap package

---

usr/lib/webapp-manager/common.py
usr/lib/webapp-manager/webapp-manager.py
usr/share/webapp-manager/webapp-manager.ui

Added Private Browsing mode for firefox, edge and other chromium based browsers.

Added support for Private Browsing mode for firefox and chromium based browsers.

---

usr/lib/webapp-manager/common.py

Title says it all. Falkon is a lightweight browser in KDE Applications. Probably needs a few more lines of code because I couldn't figure out the delete-webapp method (or is it called function?) for falkon. Btw former LMDE user, noob here, first contribution 😁

Add support for Falkon

---

usr/lib/webapp-manager/common.py

have tested, seems to work fine

Add Firefox ESR support

---

usr/lib/webapp-manager/common.py

Adding support for Microsoft Edge stable, Microsoft Edge Beta, and Microsoft Edge Dev

Add Edge Stable, Beta, Dev support

---

README.md

Before:
- Press `Ctrl`+`Tab` to cycle between opened tabs.
After:
- Press <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to cycle between opened tabs.
It will be more clear to know that you should press the key on the keyboard ⌨️

Enhance README.md with HTML5 <kbd> tag

---

usr/lib/webapp-manager/common.py

[LibreWolf](https://librewolf.net/) is a fork of Firefox, with the primary goals of privacy, security and user freedom

Add LibreWolf support

---

usr/lib/webapp-manager/webapp-manager.py

Code was throwing errors for non-uniform tabs and spaces usage. Changed 3 lines to use spaces instead of a tab.

Fixed tabs and spaces

---

usr/lib/webapp-manager/common.py

Simple addition.
Resolves issue #197

Added Flatpak Edge as browser

---

usr/lib/webapp-manager/common.py

It will be useful when the exec string will be able to be edited.
Plus, there is a [PR](https://github.com/linuxmint/webapp-manager/pull/202) to make some fields editable, that requires this refactor already open, that have conflicts related to it.

Refactor get exec string in separate method

---

usr/lib/webapp-manager/common.py

added support for firefox nightly

---

usr/lib/webapp-manager/common.py

I replaced the appends with an direct list creation and directly return it.
I also make the method static and added an return type

simplify get_supported_browsers

---

usr/lib/webapp-manager/common.py

I added type hints to `download_image`. I also unused early returns to make the function easier to read.

refactor download_image

---

usr/share/webapp-manager/firefox/profile/user.js

It seems like the user_pref to preserve cookies have changed.

Don't clear cookies in LibreWolf

---

README.md

Fixed README_tr.md link in README.md

Fix README_tr.md link

---

usr/lib/webapp-manager/webapp-manager.py

Fix firefox flatpak not showing navbar

Add firefox flatpak to show_hide_browser_widgets()

---

usr/lib/webapp-manager/common.py

This patch add support for undetected Waterfox (Flatpak).

feat: Waterfox (Flatpak) support

---

usr/share/webapp-manager/firefox/profile/chrome/userChrome.css

Fix top border in Firefox

---

usr/lib/webapp-manager/common.py

Proposed fix for issue #294 (updated)

---

usr/lib/webapp-manager/common.py

[Thorium](https://github.com/Alex313031/thorium) is an optimized browser that can be installed in Debian

add support from Thorium Browser
